{{- if .Values.bucketeer.overrideConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bucketeer.fullname" . }}-cm
data:
{{- range $k, $v := .Values.bucketeer.env.configmap }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
