{{- if .Values.bucketeer.overrideSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bucketeer.fullname" . }}-secrets
data:
{{- range $k, $v := .Values.bucketeer.env.secrets }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{- end }}
