name: chartrelease

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab #v1
        with:
          version: v3.8.1

      - name: Add helm repository dependencies
        run: |
          for chartyaml in $(find . -type f -name "Chart.yaml")
          do
            dependencies=$(cat ${chartyaml} | grep "repository: https" | awk '{print $2}' | xargs)
            subchart_root=$(echo ${chartyaml} | awk -F '[/]' '{print $1"/"$2}')
            if ! [ -z subcharts_with_dependencies ]; then
              for repo in ${dependencies}
              do
                helm repo add ${repo} ${repo}
                helm repo update
                helm dependency update ${subchart_root}
              done
            fi
          done

      - name: Lint helm chart
        run: |
          helm lint .

      - name: Install CR
        run: |
          wget -qO- https://github.com/helm/chart-releaser/releases/download/v1.3.0/chart-releaser_1.3.0_linux_amd64.tar.gz | tar -zxv cr

      - name: Test CR action on changed file(s)
        run: |
          ./cr package .

  publish:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name != 'pull_request'
    steps:
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@a3454e46a6f5ac4811069a381e646961dda2e1bf #v1.4.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
